#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit "$1" || (
    echo '🤡😂❌🤡... Haha...Learn to make commit the right way!. 😤🏀👋😤'
    false
)
echo '🚀🚀🚀🚀 You rock buddy... You are a Pro! ✅✅✅✅'
